import {FoodItemList} from "../models/food-item-list";

export const FOOD_ITEMS: FoodItemList[] = [
  {
    title: 'Vegetables', foodItems: [
      {name: 'aardappel'},
      {name: 'aardpeer'},
      {name: 'alfalfa'},
      {name: 'andijvie'},
      {name: 'artisjok'},
      {name: 'asperge'},
      {name: 'aubergine'},
      {name: 'augurk'},
      {name: 'bamboe'},
      {name: 'bieslook'},
      {name: 'biet'},
      {name: 'bindsla'},
      {name: 'bleekselderij'},
      {name: 'bloemkool'},
      {name: 'boerenkool'},
      {name: 'bosui'},
      {name: 'brandnetel'},
      {name: 'broccoli'},
      {name: 'broccolini'},
      {name: 'cassave'},
      {name: 'chilipeper'},
      {name: 'chinese kool'},
      {name: 'citroengras'},
      {name: 'courgette'},
      {name: 'erwten'},
      {name: 'eikenbladsla'},
      {name: 'flespompoen'},
      {name: 'groene kool'},
      {name: 'ijsbergsla'},
      {name: 'kappertjes'},
      {name: 'kapucijner'},
      {name: 'kervel'},
      {name: 'knoflook'},
      {name: 'knolselderij'},
      {name: 'komkommer'},
      {name: 'koolraap'},
      {name: 'koolrabi'},
      {name: 'mais'},
      {name: 'okra'},
      {name: 'olijven'},
      {name: 'paksoi'},
      {name: 'paprika'},
      {name: 'pastinaak'},
      {name: 'peterselie'},
      {name: 'peultjes'},
      {name: 'pompoen'},
      {name: 'postelein'},
      {name: 'prei'},
      {name: 'rabarber'},
      {name: 'radijs'},
      {name: 'rammenas'},
      {name: 'rode biet'},
      {name: 'rode kool'},
      {name: 'romanesco'},
      {name: 'rucola'},
      {name: 'savooiekool'},
      {name: 'schorseneren'},
      {name: 'selderij'},
      {name: 'sjalotten'},
      {name: 'sla'},
      {name: 'snijbiet'},
      {name: 'snijbonen'},
      {name: 'sperziebonen'},
      {name: 'spinazie'},
      {name: 'spitskool'},
      {name: 'spruiten'},
      {name: 'taugé'},
      {name: 'tomaten'},
      {name: 'tuinkers'},
      {name: 'ajuin'},
      {name: 'veldsla'},
      {name: 'venkel'},
      {name: 'waterkers'},
      {name: 'witloof'},
      {name: 'witte kool'},
      {name: 'wortelen'},
      {name: 'yam'},
      {name: 'zeekraal'},
      {name: 'zoete aardappel'},
      {name: 'zuurkool'},
      {name: 'nori'},
    ], selected: []
  },
  {
    title: 'Fruits', foodItems: [
      {name: 'granaatappel'},
      {name: 'jackfruit'},
      {name: 'aalbessen'},
      {name: 'aardbeien'},
      {name: 'abrikozen'},
      {name: 'ananas'},
      {name: 'appel'},
      {name: 'avocado'},
      {name: 'banaan'},
      {name: 'bergamot'},
      {name: 'bosbessen'},
      {name: 'bloedsinaasappel'},
      {name: 'bramen'},
      {name: 'cactusvijg'},
      {name: 'canataloupe'},
      {name: 'kumquat'},
      {name: 'citroen'},
      {name: 'veenbessen'},
      {name: 'dadels'},
      {name: 'druiven'},
      {name: 'frambozen'},
      {name: 'kaki'},
      {name: 'kersen'},
      {name: 'kiwi\'s' },
      {name: 'kweepeer'},
      {name: 'limoen'},
      {name: 'lotusvrucht'},
      {name: 'lychee'},
      {name: 'mandarijn'},
      {name: 'mango'},
      {name: 'meloen'},
      {name: 'nachipeer'},
      {name: 'nectarine'},
      {name: 'papaja'},
      {name: 'passievrucht'},
      {name: 'peren'},
      {name: 'perzik'},
      {name: 'pompelmoes'},
      {name: 'pruimen'},
      {name: 'rozenbottel'},
      {name: 'sinaasappel'},
      {name: 'stervrucht'},
      {name: 'vijgen'},
      {name: 'vlierbessen'},
      {name: 'moerbei'},
      {name: 'watermeloen'},
    ], selected: []
  },
  {
    title: 'Nuts', foodItems: [
      {name: 'amandelen'},
      {name: 'cashews'},
      {name: 'pistachenoten'},
      {name: 'pecannoten'},
      {name: 'macadamia noten'},
      {name: 'paranoten'},
      {name: 'pinda\'s' },
      {name: 'walnoten'},
      {name: 'hazelnoten'},
      {name: 'kastanjes'},
    ], selected: []
  },
  {
    title: 'Seeds', foodItems: [
      {name: 'pijnboompitten'},
      {name: 'kokosnoot'},
      {name: 'zonnebloempitten'},
      {name: 'lijnzaad'},
      {name: 'cacao'},
      {name: 'pompoenpitten'},
      {name: 'chiazaad'},
      {name: 'maanzaad'},
      {name: 'sesamzaad'},
      {name: 'hennepzaad'},
      {name: 'lotuszaden'},
    ], selected: []
  },
  {
    title: 'Legumes', foodItems: [
      {name: 'sojabonen'},
      {name: 'groene linzen'},
      {name: 'mungbonen'},
      {name: 'kikkererwten'},
      {name: 'zwarte bonen'},
      {name: 'limabonen'},
      {name: 'bruine bonen'},
      {name: 'black eyed peas'},
      {name: 'pinto bonen'},
      {name: 'rode linzen'},
      {name: 'zwarte linzen'},
      {name: 'cannellini bonen'},
      {name: 'witte bonen'},
      {name: 'borlotti bonen'},
      {name: 'tuinbonen'},
      {name: 'flageolets'},
      {name: 'chili bonen'},
      {name: 'bruine linzen'},
      {name: 'franse linzen'},
      {name: 'gele linzen'},
      {name: 'gele spliterwten'},
      {name: 'groene spliterwten'},
    ], selected: []
  },
  {
    title: 'Grains', foodItems: [
      {name: 'amarant'},
      {name: 'gerst'},
      {name: 'boekweit'},
      {name: 'bulgur'},
      {name: 'farro'},
      {name: 'spelt'},
      {name: 'gierst'},
      {name: 'havermout'},
      {name: 'quinoa'},
      {name: 'rijst'},
      {name: 'rogge'},
      {name: 'wilde rijst'},
      {name: 'bruine rijst'},
      {name: 'zemelen'},
      {name: 'bulgur'},
      {name: 'couscous'},
      {name: 'orzo'},
      {name: 'maisgriesmeel'},
      {name: 'tarwegriesmeel'},
    ], selected: []
  },
  {
    title: 'Spices', foodItems: [
      {name: 'anijs'},
      {name: 'laurier'},
      {name: 'basilicum'},
      {name: 'bergamot'},
      {name: 'komijn'},
      {name: 'mosterd'},
      {name: 'peper'},
      {name: 'karwij'},
      {name: 'kardemom'},
      {name: 'cayenne'},
      {name: 'cichorei'},
      {name: 'koriander'},
      {name: 'gember'},
      {name: 'mierikswortel'},
      {name: 'lavendel'},
      {name: 'citroengras'},
      {name: 'zoethout'},
      {name: 'nootmuskaat'},
      {name: 'oregano'},
      {name: 'rozemarijn'},
      {name: 'saffraan'},
      {name: 'steranijs'},
      {name: 'munt'},
      {name: 'dragon'},
      {name: 'tijm'},
      {name: 'kurkuma'},
      {name: 'vanille'},
      {name: 'wasabi'},
    ], selected: []
  }];
